volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/basverdi/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/basverdi/data/mariadb
      o: bind
      type: none
networks:
  inception:
    name: inception
    driver: bridge
services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - DB_PASS:${DB_PASS}
      - DB_USER:${DB_USER}
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build: ./wordpress
    networks:
      - inception
    volumes :
      - wordpress:/var/www/html
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: unless-stopped
  nginx:
    container_name: nginx
    build: ./nginx
    networks:
      - inception
    volumes :
      - wordpress:/var/www/html
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      - mariadb
      - wordpress
    restart: unless-stopped